### ISSUE TITLE
Access Control

### ISSUE THREAD

**Issue by reave** [Organizr/Organizr-Plugins#5]
Less an issue and more a feature request... would be nice if the non-admin user could see libraries (even if they have non shared to them) and then when they toggle the library on, instead of just enabling it, it kicks off an email to the admin requesting approval. Kind of like an access request system. 

Just a thought.

**Comment by causefx** [comment]
I would post that over here: 
https://github.com/TehMuffinMoo/PlexLibraries

**Comment by causefx** [comment]
scratch that, i add @TehMuffinMoo to this repo.

**Comment by reave** [comment]
>

**Comment by reave** [comment]
Thanks will do!
